# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SearchFilmUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWebEngineWidgets import QWebEngineView

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(991, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidgetMain = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidgetMain.setGeometry(QtCore.QRect(0, 0, 991, 651))
        self.stackedWidgetMain.setObjectName("stackedWidgetMain")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.widget = QtWidgets.QWidget(self.page_1)
        self.widget.setGeometry(QtCore.QRect(0, 0, 991, 651))
        self.widget.setObjectName("widget")
        self.buttonOpenUrl = QtWidgets.QPushButton(self.widget)
        self.buttonOpenUrl.setGeometry(QtCore.QRect(410, 260, 161, 23))
        self.buttonOpenUrl.setStyleSheet("background-color:blue;border:none;color:#ffffff;font-size:20px")
        self.buttonOpenUrl.setObjectName("buttonOpenUrl")
        self.layoutWidget_3 = QtWidgets.QWidget(self.widget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(240, 200, 520, 33))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditFilmNameMain = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEditFilmNameMain.setMinimumSize(QtCore.QSize(461, 31))
        self.lineEditFilmNameMain.setMaximumSize(QtCore.QSize(461, 16777215))
        self.lineEditFilmNameMain.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditFilmNameMain.setObjectName("lineEditFilmNameMain")
        self.horizontalLayout_2.addWidget(self.lineEditFilmNameMain)
        self.buttonSearchMain = QtWidgets.QPushButton(self.layoutWidget_3)
        self.buttonSearchMain.setMinimumSize(QtCore.QSize(51, 31))
        self.buttonSearchMain.setMaximumSize(QtCore.QSize(51, 16777215))
        self.buttonSearchMain.setObjectName("buttonSearchMain")
        self.horizontalLayout_2.addWidget(self.buttonSearchMain)
        self.stackedWidgetMain.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.layoutWidget = QtWidgets.QWidget(self.page_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 981, 641))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditFilmName = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditFilmName.setMaximumSize(QtCore.QSize(171, 20))
        self.lineEditFilmName.setObjectName("lineEditFilmName")
        self.horizontalLayout.addWidget(self.lineEditFilmName)
        self.buttonSearch = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonSearch.setMaximumSize(QtCore.QSize(51, 23))
        self.buttonSearch.setObjectName("buttonSearch")
        self.horizontalLayout.addWidget(self.buttonSearch)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2_1 = QtWidgets.QWidget()
        self.page_2_1.setObjectName("page_2_1")
        self.listWidget = QtWidgets.QListWidget(self.page_2_1)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 971, 611))
        self.listWidget.setObjectName("listWidget")
        self.stackedWidget.addWidget(self.page_2_1)
        self.page_2_2 = QtWidgets.QWidget()
        self.page_2_2.setObjectName("page_2_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.page_2_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 971, 611))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.browser = QWebEngineView(self.layoutWidget_2)
        self.browser.setObjectName("browser")
        self.gridLayout.addWidget(self.browser, 1, 0, 1, 6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.buttonBack = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonBack.setMaximumSize(QtCore.QSize(31, 23))
        self.buttonBack.setText("")
        self.buttonBack.setObjectName("buttonBack")
        self.gridLayout.addWidget(self.buttonBack, 0, 0, 1, 1)
        self.buttonDownload = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonDownload.setMaximumSize(QtCore.QSize(41, 23))
        self.buttonDownload.setText("")
        self.buttonDownload.setObjectName("buttonDownload")
        self.gridLayout.addWidget(self.buttonDownload, 0, 5, 1, 1)
        self.labelFileName = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelFileName.setMinimumSize(QtCore.QSize(671, 20))
        self.labelFileName.setText("")
        self.labelFileName.setObjectName("labelFileName")
        self.gridLayout.addWidget(self.labelFileName, 0, 4, 1, 1)
        self.buttonZoomIn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonZoomIn.setMaximumSize(QtCore.QSize(31, 16777215))
        self.buttonZoomIn.setText("")
        self.buttonZoomIn.setObjectName("buttonZoomIn")
        self.gridLayout.addWidget(self.buttonZoomIn, 0, 1, 1, 1)
        self.buttonZoomOut = QtWidgets.QPushButton(self.layoutWidget_2)
        self.buttonZoomOut.setMaximumSize(QtCore.QSize(31, 16777215))
        self.buttonZoomOut.setText("")
        self.buttonZoomOut.setObjectName("buttonZoomOut")
        self.gridLayout.addWidget(self.buttonZoomOut, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_2_2)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.stackedWidgetMain.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidgetMain.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonOpenUrl.setText(_translate("MainWindow", "www.415.net"))
        self.buttonSearchMain.setText(_translate("MainWindow", "搜索"))
        self.buttonSearch.setText(_translate("MainWindow", "搜索"))

